### ISSUE TITLE
Web Component Banner: Develop Beta 2

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds-next#39]
## Tasks

- [ ] ~Use `msg()` for strings [Localization – Lit](https://lit.dev/docs/localization/overview/#installation).~  #60.
- [ ] ~Explore logical properties for LTR in CSS [^1]~ Still using legacy styles.
- [x] Add CSS custom props
- [x] Add documentation via [Custom Elements Manifest](https://custom-elements-manifest.open-wc.org/analyzer/getting-started/#documenting-your-components) guidance
- [x] Validate against [Accessibility Checklist](https://designsystem.digital.gov/components/banner/accessibility-tests/)
- [x] Create unit tests

[^1]: uswds/uswds#5336

**Comment by mejiaj** [comment]
@heymatthenry took a shot at creating a beta issue for Banner based on items we discussed in this weeks Dev sync. 

Feel free to edit and add any items I might've missed.

**Comment by heymatthenry** [comment]
@mejiaj Awesome, thanks for doing this! Added one thing, but otherwise I think it's good to go (understanding that we aren't ready to incorporate interoperability tests yet).
